# What was the impact of natural disasters in risk pool regions?

Data Source: 
EM-DAT: The Emergency Events Database - Universit√© catholique de Louvain (UCL) - CRED, D. Guha-Sapir - https://www.emdat.be, Brussels, Belgium.

Downloaded on: 2018-11-22
    
FAQ for the database: https://www.emdat.be/frequently-asked-questions

Time frame: since risk pool establishment, so different time frames for each risk pool

Disasters that are included in this analysis: Out of all recorded natural disasters in the EMDAT database, this analysis looks at a subset of data which only includes natural disasters of the following categories: Riverine flood, Flash flood, Coastal flood, Tropical cyclone, Extra-tropical storm, Heat wave, Drought, Ground movement, Tsunami

Earthquakes (tsunamis and ground movements) were excluded later in the analysis

Damage cost is not available for all disasters recorded in the database, so value sums are MINIMUM damage (real ones higher)

Unit of damage cost: "The estimated damage is given in US $ (in thousands) in the value of the year of occurrence."

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

plt.rcParams['pdf.fonttype'] = 42
plt.rcParams['ps.fonttype'] = 42

In [2]:
df = pd.read_csv('data/EMDAT/EMDAT-climateinsurance-ev.csv', delimiter =';', encoding = 'latin-1')
df.head()

,year,iso,country_name,continent,region,disaster_subtype,disaster_type,disaster_subgroup,occurrence,Total_deaths,Injured,Affected,Homeless,Total_affected,Total_damage_K_USD
0,1998,AUS,Australia,Oceania,Australia and New Zealand,Coastal flood,Flood,Hydrological,2,4.0,NaN,1375.0,NaN,1375.0,161300.0
1,1998,JPN,Japan,Asia,Eastern Asia,Coastal flood,Flood,Hydrological,1,16.0,33.0,24000.0,NaN,24033.0,NaN
2,1998,MEX,Mexico,Americas,Central America,Coastal flood,Flood,Hydrological,1,274.0,NaN,25000.0,NaN,25000.0,602700.0
3,1999,KHM,Cambodia,Asia,South-Eastern Asia,Coastal flood,Flood,Hydrological,1,NaN,NaN,106670.0,17805.0,124475.0,NaN
4,1999,COL,Colombia,Americas,South America,Coastal flood,Flood,Hydrological,1,3.0,NaN,NaN,1100.0,1100.0,NaN

In [3]:
df['disaster_subtype'].value_counts()

Riverine flood          1191
Tropical cyclone         543
Flash flood              413
Drought                  347
Ground movement          318
Heat wave                132
Extra-tropical storm     105
Coastal flood             46
Tsunami                   30
Name: disaster_subtype, dtype: int64

In [1]:
# creating groups of countries that have received a payout (_recipients) 
# and that would have not received a payout (_potentials)

ccrif_recipients = ['Anguilla','Antigua & Barbuda','Bahamas','Barbados','Belize','Dominica','St. Kitts & Nevis','Saint Lucia','St. Vincent & the Grenadines','Trinidad & Tobago','Turks & Caicos Islands','Nicaragua','Haiti']
ccrif_potentials = ['Bermuda','Cayman Islands','Grenada','Jamaica']
ccrif_all = ccrif_recipients + ccrif_potentials


pcrafi_recipients = ['Tonga', 'Vanuatu']
pcrafi_potentials = ['Cook Islands','Marshall Islands','Samoa','Fiji','Kiribati','Micronesia','Nauru','Niue','Palau','Papua New Guinea','Solomon Islands','Tuvalu']
pcrafi_all = pcrafi_recipients + pcrafi_potentials


arc_recipients = ['Malawi','Mauritania','Niger','Senegal']
arc_potentials = ['Gambia','Kenya','Mali']
arc_optionals = ['Benin','Burkina Faso','Burundi','CAR','Chad','Comoros','Republic Congo','Djibouti','Gabon','Guinea','Guinea-Bissau','Ivory Coast','Liberia','Libya','Madagascar','Mozambique','Nigeria','Rwanda','Sahrawi','Sao Tome & Principe','Sierra Leone','Togo','Zambia','Zimbabwe']
arc_all = arc_recipients + arc_potentials

In [2]:
# make dfs that are policy for each risk pool as in regions covered and timepoint of establishment

ccrif_est = 2007
arc_est = 2014
pcrafi_est = 2016

df_ccrif = pd.DataFrame()
df_arc = pd.DataFrame()
df_pcrafi = pd.DataFrame()

pools = [ccrif_all, arc_all, pcrafi_all]

for risk_pool in pools:
    if 'Anguilla' in risk_pool:
        df_time_temp = df[df['year']>=ccrif_est]
        for country in risk_pool:
            df_temp = df_time_temp[df_time_temp['country_name']==country]
            df_ccrif = df_ccrif.append(df_temp)
    if 'Malawi' in risk_pool:
        df_time_temp = df[df['year']>=arc_est]
        for country in risk_pool:
            df_temp = df_time_temp[df_time_temp['country_name']==country]
            df_arc = df_arc.append(df_temp)
    if 'Tonga' in risk_pool:
        df_time_temp = df[df['year']>=pcrafi_est]
        for country in risk_pool:
            df_temp = df_time_temp[df_time_temp['country_name']==country]
            df_pcrafi = df_pcrafi.append(df_temp)

NameError: name 'pd' is not defined

In [6]:
risk_pool_dfs = [df_ccrif,df_arc,df_pcrafi]

In [7]:
df_ccrif.head()

,year,iso,country_name,continent,region,disaster_subtype,disaster_type,disaster_subgroup,occurrence,Total_deaths,Injured,Affected,Homeless,Total_affected,Total_damage_K_USD
3029,2017,AIA,Anguilla,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,4.0,NaN,15000.0,NaN,15000.0,200000.0
253,2010,BRB,Barbados,Americas,Caribbean,Drought,Drought,Climatological,1,NaN,NaN,NaN,NaN,NaN,NaN
1061,2007,BRB,Barbados,Americas,Caribbean,Ground movement,Earthquake,Geophysical,1,NaN,1.0,NaN,NaN,1.0,NaN
2876,2010,BRB,Barbados,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,2500.0,NaN,2500.0,NaN
3034,2017,BRB,Barbados,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,1.0,NaN,NaN,NaN,NaN,NaN

## how many people have been affected in the past by natural disasters in the risk pool regions

In [8]:
for rp in risk_pool_dfs:
    number_affected = rp['Affected'].sum()
    print("Since establishment of the risk pool", number_affected/1000000, "million people have been affected by a natural disaster there.")

Since establishment of the risk pool 13.624087 million people have been affected by a natural disaster there.
Since establishment of the risk pool 16.751402 million people have been affected by a natural disaster there.
Since establishment of the risk pool 1.279089 million people have been affected by a natural disaster there.

**Note:**
    
CCRIF: Affected 13 million, covered 12.5 million
**--> Less people covered than affected in since the establishment of the pool**
    
ARC: Affected 16 million, covered 150 million
    
PCRAFI: Affected 1 million, covered 4.5 million

## how many disasters happened in that time in that risk pool region

In [9]:
for rp in risk_pool_dfs:
    number_disasters = rp['occurrence'].sum()
    print("Since establishment of the risk pool", number_disasters , "disasters happened there.")

Since establishment of the risk pool 93 disasters happened there.
Since establishment of the risk pool 14 disasters happened there.
Since establishment of the risk pool 13 disasters happened there.

**Note:**

CCRIF: 93 natural disasters, 44 payouts (less than every second, only half of all disasters triggered a payout)

ARC: 14 natural disasters, 5 payouts (one in three disasters triggered a payout, a third of all disasters, 35% triggered a payout)

PCRAFI: 13 natural disasters, 3 payouts (one in five disasters, 23% triggered a payout)

## how much damage did disasters cause in the risk pool regions since establishment of the respective pool

In [10]:
for rp in risk_pool_dfs:
    damage_caused = rp['Total_damage_K_USD'].sum()
    print("Since establishment of the risk pool, natural disasters caused US$", damage_caused/1000 , "million of damage there.")

Since establishment of the risk pool, natural disasters caused US$ 13101.594 million of damage there.
Since establishment of the risk pool, natural disasters caused US$ 390.0 million of damage there.
Since establishment of the risk pool, natural disasters caused US$ 661.0 million of damage there.

**Note**:
    
CCRIF: US$ 13101 million (13 billion) damage caused, payouts covered 139.4 million (equals 1 percent) - payins by members: 226 million

ARC: US$ 390 million damage caused, payouts covered 36.6 million (equals 9.4 percent)

PCRAFI: US$ 661 million damage caused, payouts covered 6.7 million (equals 1 percent)

# only look at disasters insured under each risk pool

In [11]:
arc_disaster_types = ['Drought']
ccrif_disaster_types = ['Tropical cyclone', 'Riverine flood', 'Flash flood', 'Ground movement', 'Tsunami']
pcrafi_disaster_types = ['Tropical cyclone']

In [12]:
df_ccrif_policy = pd.DataFrame()
df_arc_policy = pd.DataFrame()
df_pcrafi_policy = pd.DataFrame()

pools = [ccrif_all, arc_all, pcrafi_all]

for risk_pool in pools:
    if 'Anguilla' in risk_pool:
        df_time_temp2 = df[df['year']>=ccrif_est]
        for country in risk_pool:
            df_temp2 = df_time_temp2[df_time_temp2['country_name']==country]
            for disaster_type in ccrif_disaster_types:
                df_type_temp = df_temp2[df_temp2['disaster_subtype']==disaster_type]
                df_ccrif_policy = df_ccrif_policy.append(df_type_temp)
    if 'Malawi' in risk_pool:
        df_time_temp2 = df[df['year']>=arc_est]
        for country in risk_pool:
            df_temp2 = df_time_temp2[df_time_temp2['country_name']==country]
            for disaster_type in arc_disaster_types:
                df_type_temp = df_temp2[df_temp2['disaster_subtype']==disaster_type]
                df_arc_policy = df_arc_policy.append(df_type_temp)
    if 'Tonga' in risk_pool:
        df_time_temp2 = df[df['year']>=pcrafi_est]
        for country in risk_pool:
            df_temp2 = df_time_temp2[df_time_temp2['country_name']==country]
            for disaster_type in pcrafi_disaster_types:
                df_type_temp = df_temp2[df_temp2['disaster_subtype']==disaster_type]
                df_pcrafi_policy = df_pcrafi_policy.append(df_type_temp)

In [13]:
df_arc_policy

,year,iso,country_name,continent,region,disaster_subtype,disaster_type,disaster_subgroup,occurrence,Total_deaths,Injured,Affected,Homeless,Total_affected,Total_damage_K_USD
344,2015,MWI,Malawi,Africa,Eastern Africa,Drought,Drought,Climatological,1,NaN,NaN,6700000.0,NaN,6700000.0,NaN
379,2017,MRT,Mauritania,Africa,Western Africa,Drought,Drought,Climatological,1,NaN,NaN,3893774.0,NaN,3893774.0,NaN
327,2014,SEN,Senegal,Africa,Western Africa,Drought,Drought,Climatological,1,NaN,NaN,639702.0,NaN,639702.0,NaN
323,2014,KEN,Kenya,Africa,Eastern Africa,Drought,Drought,Climatological,1,NaN,NaN,1600000.0,NaN,1600000.0,NaN
364,2016,KEN,Kenya,Africa,Eastern Africa,Drought,Drought,Climatological,1,NaN,NaN,3000000.0,NaN,3000000.0,NaN

In [14]:
df_pcrafi_policy

,year,iso,country_name,continent,region,disaster_subtype,disaster_type,disaster_subgroup,occurrence,Total_deaths,Injured,Affected,Homeless,Total_affected,Total_damage_K_USD
3026,2016,TON,Tonga,Oceania,Polynesia,Tropical cyclone,Storm,Meteorological,3,NaN,NaN,392.0,NaN,392.0,NaN
3091,2018,TON,Tonga,Oceania,Polynesia,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,87000.0,NaN,87000.0,NaN
3070,2017,VUT,Vanuatu,Oceania,Melanesia,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,2564.0,NaN,2564.0,NaN
3088,2018,WSM,Samoa,Oceania,Polynesia,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,NaN,NaN,NaN,NaN
3015,2016,FJI,Fiji,Oceania,Melanesia,Tropical cyclone,Storm,Meteorological,2,47.0,144.0,545414.0,NaN,545558.0,600000.0
3078,2018,FJI,Fiji,Oceania,Melanesia,Tropical cyclone,Storm,Meteorological,1,5.0,NaN,89950.0,NaN,89950.0,NaN

In [15]:
df_ccrif_policy

,year,iso,country_name,continent,region,disaster_subtype,disaster_type,disaster_subgroup,occurrence,Total_deaths,Injured,Affected,Homeless,Total_affected,Total_damage_K_USD
3029,2017,AIA,Anguilla,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,4.0,NaN,15000.0,NaN,15000.0,200000.0
2876,2010,BRB,Barbados,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,2500.0,NaN,2500.0,NaN
3034,2017,BRB,Barbados,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,1.0,NaN,NaN,NaN,NaN,NaN
1061,2007,BRB,Barbados,Americas,Caribbean,Ground movement,Earthquake,Geophysical,1,NaN,1.0,NaN,NaN,1.0,NaN
2791,2007,BLZ,Belize,Americas,Central America,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,20000.0,NaN,20000.0,14847.0
2829,2008,BLZ,Belize,Americas,Central America,Tropical cyclone,Storm,Meteorological,1,7.0,NaN,10000.0,NaN,10000.0,NaN
2877,2010,BLZ,Belize,Americas,Central America,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,NaN,NaN,NaN,NaN
3012,2016,BLZ,Belize,Americas,Central America,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,10355.0,NaN,10355.0,NaN
1952,2008,BLZ,Belize,Americas,Central America,Riverine flood,Flood,Hydrological,1,1.0,NaN,38000.0,NaN,38000.0,9697.0
2794,2007,DMA,Dominica,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,2.0,30.0,7500.0,NaN,7530.0,20000.0
2910,2011,DMA,Dominica,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,144.0,96.0,240.0,NaN
2991,2015,DMA,Dominica,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,30.0,20.0,28000.0,574.0,28594.0,482810.0
3039,2017,DMA,Dominica,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,64.0,100.0,71293.0,NaN,71393.0,1456000.0
2821,2007,LCA,Saint Lucia,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,1.0,NaN,NaN,NaN,NaN,40000.0
2899,2010,LCA,Saint Lucia,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,14.0,NaN,181000.0,NaN,181000.0,500.0
2388,2013,LCA,Saint Lucia,Americas,Caribbean,Riverine flood,Flood,Hydrological,1,6.0,NaN,19984.0,NaN,19984.0,NaN
759,2010,LCA,Saint Lucia,Americas,Caribbean,Flash flood,Flood,Hydrological,1,NaN,NaN,2000.0,NaN,2000.0,NaN
1072,2007,LCA,Saint Lucia,Americas,Caribbean,Ground movement,Earthquake,Geophysical,1,NaN,NaN,NaN,NaN,NaN,NaN
2814,2007,NIC,Nicaragua,Americas,Central America,Tropical cyclone,Storm,Meteorological,1,188.0,NaN,188726.0,NaN,188726.0,NaN
2845,2008,NIC,Nicaragua,Americas,Central America,Tropical cyclone,Storm,Meteorological,1,13.0,NaN,25000.0,NaN,25000.0,NaN
2868,2009,NIC,Nicaragua,Americas,Central America,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,19897.0,NaN,19897.0,NaN
2895,2010,NIC,Nicaragua,Americas,Central America,Tropical cyclone,Storm,Meteorological,2,5.0,NaN,NaN,NaN,NaN,NaN
3022,2016,NIC,Nicaragua,Americas,Central America,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,10570.0,NaN,10570.0,NaN
3057,2017,NIC,Nicaragua,Americas,Central America,Tropical cyclone,Storm,Meteorological,1,15.0,NaN,39200.0,NaN,39200.0,NaN
1916,2007,NIC,Nicaragua,Americas,Central America,Riverine flood,Flood,Hydrological,1,10.0,NaN,24000.0,NaN,24000.0,NaN
1996,2008,NIC,Nicaragua,Americas,Central America,Riverine flood,Flood,Hydrological,2,17.0,NaN,14188.0,NaN,14188.0,NaN
2071,2009,NIC,Nicaragua,Americas,Central America,Riverine flood,Flood,Hydrological,2,NaN,NaN,6885.0,NaN,6885.0,NaN
2156,2010,NIC,Nicaragua,Americas,Central America,Riverine flood,Flood,Hydrological,2,66.0,NaN,75860.0,NaN,75860.0,NaN
2232,2011,NIC,Nicaragua,Americas,Central America,Riverine flood,Flood,Hydrological,1,17.0,18.0,143000.0,NaN,143018.0,NaN
2301,2012,NIC,Nicaragua,Americas,Central America,Riverine flood,Flood,Hydrological,1,9.0,NaN,29500.0,NaN,29500.0,NaN
2377,2013,NIC,Nicaragua,Americas,Central America,Riverine flood,Flood,Hydrological,1,27.0,NaN,14149.0,NaN,14149.0,NaN
2433,2014,NIC,Nicaragua,Americas,Central America,Riverine flood,Flood,Hydrological,1,NaN,NaN,60345.0,NaN,60345.0,NaN
2486,2015,NIC,Nicaragua,Americas,Central America,Riverine flood,Flood,Hydrological,1,2.0,NaN,3750.0,NaN,3750.0,NaN
1170,2014,NIC,Nicaragua,Americas,Central America,Ground movement,Earthquake,Geophysical,1,2.0,266.0,12015.0,NaN,12281.0,3000.0
2800,2007,HTI,Haiti,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,3,102.0,141.0,114680.0,260.0,115081.0,NaN
2837,2008,HTI,Haiti,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,4,698.0,86.0,246160.0,30.0,246276.0,NaN
2885,2010,HTI,Haiti,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,21.0,NaN,5020.0,NaN,5020.0,NaN
2913,2011,HTI,Haiti,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,2,3.0,4.0,2500.0,540.0,3044.0,NaN
2935,2012,HTI,Haiti,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,2,88.0,27.0,176500.0,33330.0,209857.0,254000.0
2993,2015,HTI,Haiti,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,5.0,3.0,NaN,1966.0,1969.0,NaN
3044,2017,HTI,Haiti,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,2,4.0,17.0,40075.0,NaN,40092.0,NaN
1898,2007,HTI,Haiti,Americas,Caribbean,Riverine flood,Flood,Hydrological,4,61.0,92.0,89020.0,15849.0,104961.0,NaN
2053,2009,HTI,Haiti,Americas,Caribbean,Riverine flood,Flood,Hydrological,2,21.0,NaN,2500.0,9910.0,12410.0,NaN
2134,2010,HTI,Haiti,Americas,Caribbean,Riverine flood,Flood,Hydrological,2,40.0,NaN,22085.0,NaN,22085.0,NaN
2214,2011,HTI,Haiti,Americas,Caribbean,Riverine flood,Flood,Hydrological,2,36.0,8.0,4430.0,NaN,4438.0,NaN
2286,2012,HTI,Haiti,Americas,Caribbean,Riverine flood,Flood,Hydrological,3,42.0,NaN,26465.0,NaN,26465.0,NaN
2356,2013,HTI,Haiti,Americas,Caribbean,Riverine flood,Flood,Hydrological,1,6.0,NaN,NaN,33265.0,33265.0,NaN
2473,2015,HTI,Haiti,Americas,Caribbean,Riverine flood,Flood,Hydrological,1,6.0,NaN,45000.0,NaN,45000.0,NaN
2511,2016,HTI,Haiti,Americas,Caribbean,Riverine flood,Flood,Hydrological,3,41.0,7662.0,40620.0,2780.0,51062.0,2000.0
734,2009,HTI,Haiti,Americas,Caribbean,Flash flood,Flood,Hydrological,1,NaN,NaN,296.0,NaN,296.0,NaN
750,2010,HTI,Haiti,Americas,Caribbean,Flash flood,Flood,Hydrological,1,4.0,2.0,NaN,NaN,2.0,NaN
804,2014,HTI,Haiti,Americas,Caribbean,Flash flood,Flood,Hydrological,1,12.0,NaN,30000.0,NaN,30000.0,NaN
1101,2010,HTI,Haiti,Americas,Caribbean,Ground movement,Earthquake,Geophysical,1,222570.0,300000.0,3400000.0,NaN,3700000.0,8000000.0
1221,2018,HTI,Haiti,Americas,Caribbean,Ground movement,Earthquake,Geophysical,1,15.0,333.0,350000.0,NaN,350333.0,NaN
2804,2007,JAM,Jamaica,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,2,5.0,NaN,32000.0,1188.0,33188.0,300000.0
2840,2008,JAM,Jamaica,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,2,13.0,NaN,4000.0,NaN,4000.0,66198.0
2889,2010,JAM,Jamaica,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,15.0,26.0,2480.0,NaN,2506.0,150000.0
2937,2012,JAM,Jamaica,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,1.0,NaN,215850.0,NaN,215850.0,16542.0

In [16]:
ccrif_policy_damage = df_ccrif_policy['Total_damage_K_USD'].sum()
print('Insured events caused a damage of',ccrif_policy_damage/1000,'million USD.')

Insured events caused a damage of 11015.594 million USD.

Note: For CCRIF, even if you only include disaster types that are potentially covered by a risk insurance in the damage calculation, the damage caused is 11015 million (or 11 billion) US Dollar, compared to payouts of 131 million US Dollar (equals 1.2 percent)

In [17]:
ccrif_policy_damage_wo_eq = df_ccrif_policy[df_ccrif_policy['disaster_type']!= "Earthquake"]['Total_damage_K_USD'].sum()
print('Insured events caused a damage of',ccrif_policy_damage_wo_eq/1000,'million USD.')

Insured events caused a damage of 3012.594 million USD.

EXCLUDING EARTHQUAKES, for CCRIF, even if you only include disaster types that are potentially covered by a risk insurance in the damage calculation, the damage caused is 3012.594 million US Dollar, compared to payouts of 121.9 million US Dollar (equals 4 percent)

## Repeat first analysis, without earthquake data

In [17]:
df_woe = df[df['disaster_type']!= 'Earthquake']
df_woe

,year,iso,country_name,continent,region,disaster_subtype,disaster_type,disaster_subgroup,occurrence,Total_deaths,Injured,Affected,Homeless,Total_affected,Total_damage_K_USD
0,1998,AUS,Australia,Oceania,Australia and New Zealand,Coastal flood,Flood,Hydrological,2,4.0,NaN,1375.0,NaN,1375.0,161300.0
1,1998,JPN,Japan,Asia,Eastern Asia,Coastal flood,Flood,Hydrological,1,16.0,33.0,24000.0,NaN,24033.0,NaN
2,1998,MEX,Mexico,Americas,Central America,Coastal flood,Flood,Hydrological,1,274.0,NaN,25000.0,NaN,25000.0,602700.0
3,1999,KHM,Cambodia,Asia,South-Eastern Asia,Coastal flood,Flood,Hydrological,1,NaN,NaN,106670.0,17805.0,124475.0,NaN
4,1999,COL,Colombia,Americas,South America,Coastal flood,Flood,Hydrological,1,3.0,NaN,NaN,1100.0,1100.0,NaN
5,1999,MEX,Mexico,Americas,Central America,Coastal flood,Flood,Hydrological,1,636.0,60.0,530000.0,86000.0,616060.0,451300.0
6,1999,NIC,Nicaragua,Americas,Central America,Coastal flood,Flood,Hydrological,1,11.0,NaN,100000.0,7105.0,107105.0,500.0
7,1999,PAN,Panama,Americas,Central America,Coastal flood,Flood,Hydrological,1,1.0,NaN,NaN,NaN,NaN,NaN
8,1999,THA,Thailand,Asia,South-Eastern Asia,Coastal flood,Flood,Hydrological,2,10.0,NaN,170000.0,200.0,170200.0,267.0
9,1999,VEN,Venezuela (Bolivarian Republic of),Americas,South America,Coastal flood,Flood,Hydrological,1,5.0,368.0,51000.0,8000.0,59368.0,NaN
10,1999,VNM,Viet Nam,Asia,South-Eastern Asia,Coastal flood,Flood,Hydrological,1,622.0,412.0,3414000.0,90000.0,3504412.0,237000.0
11,2000,BGD,Bangladesh,Asia,Southern Asia,Coastal flood,Flood,Hydrological,1,1.0,10.0,NaN,12000.0,12010.0,NaN
12,2000,FJI,Fiji,Oceania,Melanesia,Coastal flood,Flood,Hydrological,1,4.0,NaN,NaN,NaN,NaN,NaN
13,2000,JPN,Japan,Asia,Eastern Asia,Coastal flood,Flood,Hydrological,1,18.0,110.0,360000.0,NaN,360110.0,7440000.0
14,2000,PHL,Philippines (the),Asia,South-Eastern Asia,Coastal flood,Flood,Hydrological,2,5.0,NaN,6508.0,5250.0,11758.0,NaN
15,2000,RUS,Russian Federation (the),Europe,Eastern Europe,Coastal flood,Flood,Hydrological,2,NaN,NaN,7181.0,NaN,7181.0,8622.0
16,2001,AUS,Australia,Oceania,Australia and New Zealand,Coastal flood,Flood,Hydrological,1,NaN,NaN,670.0,NaN,670.0,13000.0
17,2001,MWI,Malawi,Africa,Eastern Africa,Coastal flood,Flood,Hydrological,1,59.0,NaN,500000.0,NaN,500000.0,6700.0
18,2001,MOZ,Mozambique,Africa,Eastern Africa,Coastal flood,Flood,Hydrological,1,79.0,NaN,549326.0,NaN,549326.0,36000.0
19,2001,RUS,Russian Federation (the),Europe,Eastern Europe,Coastal flood,Flood,Hydrological,1,11.0,NaN,300000.0,NaN,300000.0,33000.0
20,2001,VNM,Viet Nam,Asia,South-Eastern Asia,Coastal flood,Flood,Hydrological,1,NaN,NaN,3000.0,NaN,3000.0,NaN
21,2002,CHN,China,Asia,Eastern Asia,Coastal flood,Flood,Hydrological,1,61.0,15.0,NaN,NaN,15.0,NaN
22,2002,HND,Honduras,Americas,Central America,Coastal flood,Flood,Hydrological,1,NaN,NaN,1720.0,NaN,1720.0,NaN
23,2002,PHL,Philippines (the),Asia,South-Eastern Asia,Coastal flood,Flood,Hydrological,2,44.0,59.0,10500.0,NaN,10559.0,NaN
24,2003,DOM,Dominican Republic (the),Americas,Caribbean,Coastal flood,Flood,Hydrological,1,9.0,3.0,65000.0,NaN,65003.0,42620.0
25,2003,MWI,Malawi,Africa,Eastern Africa,Coastal flood,Flood,Hydrological,1,8.0,NaN,18500.0,NaN,18500.0,NaN
26,2003,MEX,Mexico,Americas,Central America,Coastal flood,Flood,Hydrological,1,2.0,NaN,50000.0,NaN,50000.0,NaN
27,2003,MOZ,Mozambique,Africa,Eastern Africa,Coastal flood,Flood,Hydrological,1,4.0,3.0,100000.0,NaN,100003.0,NaN
28,2003,VNM,Viet Nam,Asia,South-Eastern Asia,Coastal flood,Flood,Hydrological,1,52.0,29.0,216745.0,5000.0,221774.0,32000.0
29,2006,HTI,Haiti,Americas,Caribbean,Coastal flood,Flood,Hydrological,1,NaN,NaN,4690.0,NaN,4690.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3065,2017,LKA,Sri Lanka,Asia,Southern Asia,Tropical cyclone,Storm,Meteorological,1,27.0,77.0,160000.0,NaN,160077.0,346000.0
3066,2017,TWN,Taiwan (Province of China),Asia,Eastern Asia,Tropical cyclone,Storm,Meteorological,1,1.0,131.0,NaN,NaN,131.0,17200.0
3067,2017,THA,Thailand,Asia,South-Eastern Asia,Tropical cyclone,Storm,Meteorological,2,NaN,NaN,28560.0,NaN,28560.0,NaN
3068,2017,TCA,Turks and Caicos Islands (the),Americas,Caribbean,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,NaN,NaN,NaN,500000.0
3069,2017,USA,United States of America (the),Americas,Northern America,Tropical cyclone,Storm,Meteorological,4,150.0,24.0,555060.0,97000.0,652084.0,152250000.0
3070,2017,VUT,Vanuatu,Oceania,Melanesia,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,2564.0,NaN,2564.0,NaN
3071,2017,VNM,Viet Nam,Asia,South-Eastern Asia,Tropical cyclone,Storm,Meteorological,4,147.0,113.0,5042900.0,NaN,5043013.0,2985000.0
3072,2017,VGB,Virgin Island (British),Americas,Caribbean,Tropical cyclone,Storm,Meteorological,2,9.0,NaN,NaN,NaN,NaN,3000000.0
3073,2017,VIR,Virgin Island (U.S.),Americas,Caribbean,Tropical cyclone,Storm,Meteorological,2,7.0,NaN,NaN,NaN,NaN,NaN
3074,2017,ZWE,Zimbabwe,Africa,Eastern Africa,Tropical cyclone,Storm,Meteorological,1,251.0,128.0,100000.0,12895.0,113023.0,189000.0
3075,2018,CHN,China,Asia,Eastern Asia,Tropical cyclone,Storm,Meteorological,3,16.0,NaN,16200.0,300.0,16500.0,1528000.0
3076,2018,CUB,Cuba,Americas,Caribbean,Tropical cyclone,Storm,Meteorological,2,9.0,NaN,40540.0,NaN,40540.0,NaN
3077,2018,DJI,Djibouti,Africa,Eastern Africa,Tropical cyclone,Storm,Meteorological,1,2.0,NaN,25000.0,NaN,25000.0,NaN
3078,2018,FJI,Fiji,Oceania,Melanesia,Tropical cyclone,Storm,Meteorological,1,5.0,NaN,89950.0,NaN,89950.0,NaN
3079,2018,HKG,Hong Kong,Asia,Eastern Asia,Tropical cyclone,Storm,Meteorological,1,NaN,300.0,NaN,NaN,300.0,NaN
3080,2018,IND,India,Asia,Southern Asia,Tropical cyclone,Storm,Meteorological,1,7.0,NaN,300000.0,NaN,300000.0,NaN
3081,2018,JPN,Japan,Asia,Eastern Asia,Tropical cyclone,Storm,Meteorological,1,17.0,600.0,3300.0,NaN,3900.0,NaN
3082,2018,LAO,Lao People's Democratic Republic (the),Asia,South-Eastern Asia,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,120000.0,NaN,120000.0,NaN
3083,2018,MDG,Madagascar,Africa,Eastern Africa,Tropical cyclone,Storm,Meteorological,2,94.0,NaN,211000.0,NaN,211000.0,NaN
3084,2018,MUS,Mauritius,Africa,Eastern Africa,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,30000.0,NaN,30000.0,NaN
3085,2018,OMN,Oman,Asia,Western Asia,Tropical cyclone,Storm,Meteorological,1,6.0,NaN,NaN,NaN,NaN,NaN
3086,2018,PHL,Philippines (the),Asia,South-Eastern Asia,Tropical cyclone,Storm,Meteorological,4,124.0,9.0,2837151.0,NaN,2837160.0,725236.0
3087,2018,REU,R√©union,Africa,Eastern Africa,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,200.0,NaN,200.0,NaN
3088,2018,WSM,Samoa,Oceania,Polynesia,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,NaN,NaN,NaN,NaN
3089,2018,SOM,Somalia,Africa,Eastern Africa,Tropical cyclone,Storm,Meteorological,1,55.0,NaN,670000.0,NaN,670000.0,NaN
3090,2018,TWN,Taiwan (Province of China),Asia,Eastern Asia,Tropical cyclone,Storm,Meteorological,1,7.0,140.0,6000.0,NaN,6140.0,34000.0
3091,2018,TON,Tonga,Oceania,Polynesia,Tropical cyclone,Storm,Meteorological,1,NaN,NaN,87000.0,NaN,87000.0,NaN
3092,2018,USA,United States of America (the),Americas,Northern America,Tropical cyclone,Storm,Meteorological,2,83.0,NaN,NaN,NaN,NaN,10000000.0
3093,2018,VNM,Viet Nam,Asia,South-Eastern Asia,Tropical cyclone,Storm,Meteorological,3,48.0,NaN,146000.0,NaN,146000.0,222000.0
3094,2018,YEM,Yemen,Asia,Western Asia,Tropical cyclone,Storm,Meteorological,1,24.0,NaN,750.0,NaN,750.0,NaN

In [18]:
df_ccrif_woe = pd.DataFrame()
df_arc_woe = pd.DataFrame()
df_pcrafi_woe = pd.DataFrame()

for risk_pool in pools:
    if 'Anguilla' in risk_pool:
        df_time_temp3 = df_woe[df_woe['year']>=ccrif_est]
        for country in risk_pool:
            df_temp3 = df_time_temp3[df_time_temp3['country_name']==country]
            df_ccrif_woe = df_ccrif_woe.append(df_temp3)
    if 'Malawi' in risk_pool:
        df_time_temp3 = df_woe[df_woe['year']>=arc_est]
        for country in risk_pool:
            df_temp3 = df_time_temp3[df_time_temp3['country_name']==country]
            df_arc_woe = df_arc_woe.append(df_temp3)
    if 'Tonga' in risk_pool:
        df_time_temp3 = df_woe[df_woe['year']>=pcrafi_est]
        for country in risk_pool:
            df_temp3 = df_time_temp3[df_time_temp3['country_name']==country]
            df_pcrafi_woe = df_pcrafi_woe.append(df_temp3)

In [19]:
risk_pool_dfs_woe = [df_ccrif_woe,df_arc_woe,df_pcrafi_woe]

for rp in risk_pool_dfs_woe:
    number_affected_woe = rp['Affected'].sum()
    print("Excluding earthquakes, since establishment of the risk pool", number_affected_woe/1000000, "million people have been affected by a natural disaster there.")

Excluding earthquakes, since establishment of the risk pool 9.862072 million people have been affected by a natural disaster there.
Excluding earthquakes, since establishment of the risk pool 16.751402 million people have been affected by a natural disaster there.
Excluding earthquakes, since establishment of the risk pool 0.72532 million people have been affected by a natural disaster there.

In [20]:
for rp in risk_pool_dfs_woe:
    number_disasters_woe = rp['occurrence'].sum()
    print("Excluding earthquakes, since establishment of the risk pool", number_disasters_woe , "disasters happened there.")

Excluding earthquakes, since establishment of the risk pool 88 disasters happened there.
Excluding earthquakes, since establishment of the risk pool 14 disasters happened there.
Excluding earthquakes, since establishment of the risk pool 9 disasters happened there.

CCRIF: 88 natural disasters, 38 payouts (less than every second, less than half of all disasters triggered a payout)

ARC: 14 natural disasters, 5 payouts (one in three disasters triggered a payout, a third of all disasters, 35% triggered a payout)

PCRAFI: 9 natural disasters, 3 payouts (one in three disasters, 33% triggered a payout)

In [21]:
for rp in risk_pool_dfs_woe:
    damage_caused_woe = rp['Total_damage_K_USD'].sum()
    print("Excluding earthquakes, since establishment natural disasters caused US$", damage_caused_woe/1000 , "million of damage there.")

Excluding earthquakes, since establishment natural disasters caused US$ 5098.594 million of damage there.
Excluding earthquakes, since establishment natural disasters caused US$ 390.0 million of damage there.
Excluding earthquakes, since establishment natural disasters caused US$ 600.0 million of damage there.

**Note**:
    
CCRIF: US$ 5098 million (5 billion) damage caused, payouts covered 121.9 million (equals 2.4 percent) - payins by members: 226 million

ARC: US$ 390 million damage caused, payouts covered 36.6 million (equals 9.4 percent)

PCRAFI: US$ 600 million damage caused, payouts covered 6.7 million (equals 1.1 percent)